server:
  port: ${BOOKING_SERVER_PORT:8002}
  address: 0.0.0.0
  servlet:
    context-path: /booking-service
spring:
  application:
    name: '@name@'
    version: '@revision@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BOOKING_DB_HOST:localhost}:${BOOKING_DB_PORT:3312}/${BOOKING_DB_NAME:booking_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: ${BOOKING_DB_USERNAME:user}
    password: ${BOOKING_DB_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:mysql://${BOOKING_DB_HOST:localhost}:${BOOKING_DB_PORT:3312}/${BOOKING_DB_NAME:booking_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    user: ${BOOKING_DB_USERNAME:user}
    password: ${BOOKING_DB_PASSWORD:password}
  docker:
    compose:
      file: '.\docker\common.yml'
      enabled: ${ENABLE_BUILTIN_DOCKER_COMPOSE:true}
management:
  endpoints:
    web:
      exposure:
        include: "*"
