version: '3.8'

services:
  hotel-db:
    image: 'mysql:8.0.33'
    container_name: hotel-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Cuiaba
      MYSQL_DATABASE: hotel_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    stdin_open: true
    tty: true
    expose:
      - 3311
    restart: on-failure
    ports:
      - '3311:3306'
    volumes:
      - ./scripts/hotel-seed-script.sql:/docker-entrypoint-initdb.d/init.sql
      - /opt/hotel-booking-system/hotel-db/mysql:/var/lib/mysql
    networks:
      - hotel-booking-system-network

networks:
  hotel-booking-system-network:
    driver: bridge
    name: hotel-booking-system-network
