version: '3.8'

services:
  hotel-service:
    image: com.hotel.booking.system/hotel-service:latest
    container_name: hotel-service
    restart: on-failure
    depends_on:
      - hotel-db
    environment:
      HOTEL_SERVER_PORT: 8001
      HOTEL_DB_HOST: hotel-db
      HOTEL_DB_PORT: 3306
      HOTEL_DB_NAME: hotel_db
      HOTEL_DB_USERNAME: user
      HOTEL_DB_PASSWORD: password
      ENABLE_BUILTIN_DOCKER_COMPOSE: false
      RABBITMQ_HOST: hotel-booking-system-queue
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: root
    ports:
      - '8001:8001'
    networks:
      - hotel-booking-system-network

  booking-service:
    image: com.hotel.booking.system/booking-service:latest
    container_name: booking-service
    restart: on-failure
    depends_on:
      - booking-db
    environment:
      BOOKING_SERVER_PORT: 8002
      BOOKING_DB_HOST: booking-db
      BOOKING_DB_PORT: 3306
      BOOKING_DB_NAME: booking_db
      BOOKING_DB_USERNAME: user
      BOOKING_DB_PASSWORD: password
      ENABLE_BUILTIN_DOCKER_COMPOSE: false
    ports:
      - '8002:8002'
    networks:
      - hotel-booking-system-network
