server:
  port: ${HOTEL_SERVER_PORT:8001}
  address: 0.0.0.0
  servlet:
    context-path: /hotel-service
spring:
  application:
    name: '@name@'
    version: '@revision@'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:root}
    password: ${RABBITMQ_PASSWORD:root}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOTEL_DB_HOST:localhost}:${HOTEL_DB_PORT:3311}/${HOTEL_DB_NAME:hotel_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    username: ${HOTEL_DB_USERNAME:user}
    password: ${HOTEL_DB_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  flyway:
    url: jdbc:mysql://${HOTEL_DB_HOST:localhost}:${HOTEL_DB_PORT:3311}/${HOTEL_DB_NAME:hotel_db}?autoReconnect=true&useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
    user: ${HOTEL_DB_USERNAME:user}
    password: ${HOTEL_DB_PASSWORD:password}
  docker:
    compose:
      file: '.\docker\common.yml'
      enabled: ${ENABLE_BUILTIN_DOCKER_COMPOSE:false}
management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  rabbitmq:
    exchange:
      booking-room: exchange.booking-room
      payment: exchange.payment
      customer-booking: exchange.customer-booking
    routing-key:
      booking-room-requested: routing-key.booking-room-requested
      booking-room-confirmation: routing-key.booking-room-confirmation
      booking-room-status-changed: routing-key.booking-room-status-changed
      payment-request: routing-key.payment-request
      payment-confirmation: routing-key.payment-confirmation
      customer-booking-update: routing-key.customer-booking-update
    queue:
      booking-room-requested: booking-room-requested
      booking-room-confirmation: booking-room-confirmation
      booking-room-status-changed: booking-room-status-changed
      payment-request: payment-request
      payment-confirmation: payment-confirmation
      customer-booking-update: customer-booking-update


